# Generated by Django 4.1.6 on 2024-07-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('layout_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipBase',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('tip_volume', models.FloatField()),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.backendbase')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('tip_racks', models.ManyToManyField(to='layout_item.layoutitembase')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='HamiltonEETipBase',
            fields=[
                ('tipbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tip.tipbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tip.tipbase',),
        ),
        migrations.CreateModel(
            name='HamiltonFTR',
            fields=[
                ('tipbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tip.tipbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tip.tipbase',),
        ),
        migrations.CreateModel(
            name='HamiltonNTR',
            fields=[
                ('tipbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tip.tipbase')),
                ('tip_rack_waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout_item.layoutitembase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tip.tipbase',),
        ),
    ]
