# Generated by Django 4.1.6 on 2024-07-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0001_initial'),
        ('tip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamiltonEEFTR1000uL',
            fields=[
                ('hamiltoneetipbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tip.hamiltoneetipbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tip.hamiltoneetipbase',),
        ),
        migrations.CreateModel(
            name='HamiltonEENTR',
            fields=[
                ('hamiltoneetipbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tip.hamiltoneetipbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tip.hamiltoneetipbase',),
        ),
        migrations.AddField(
            model_name='hamiltoneetipbase',
            name='tip_rack_waste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='layout_item.layoutitembase'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HamiltonEETipStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveSmallIntegerField()),
                ('stack_number', models.PositiveSmallIntegerField()),
                ('tip_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout_item.layoutitembase')),
            ],
        ),
        migrations.AddField(
            model_name='hamiltoneetipbase',
            name='tip_stacks',
            field=models.ManyToManyField(to='tip.hamiltoneetipstack'),
        ),
    ]
