# Generated by Django 5.1.1 on 2024-10-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistcolumnvalue',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
