# Generated by Django 5.1.2 on 2024-11-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_valid", models.BooleanField(default=False, editable=False)),
                ("row", models.IntegerField()),
                ("column", models.IntegerField()),
                (
                    "left_child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="block.blockbase",
                    ),
                ),
                (
                    "left_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="block.blockbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ActivateContainer",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("meta_data_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("meta_data_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Dilute",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("solution", models.CharField(max_length=255, null=True)),
                ("target_concentration", models.CharField(max_length=255, null=True)),
                ("target_volume", models.CharField(max_length=255, null=True)),
                (
                    "min_aspirate_mix_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "min_dispense_mix_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "max_source_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="DocumentNumber",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("meta_data_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Incubate",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("time", models.CharField(max_length=255, null=True)),
                ("temperature", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="IncubateAndShake",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("time", models.CharField(max_length=255, null=True)),
                ("temperature", models.CharField(max_length=255, null=True)),
                ("shaking_rpm", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="MeasureConcentration",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("output_worklist_column", models.CharField(max_length=255, null=True)),
                ("extinction_coefficient", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Merge",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("container_name", models.CharField(max_length=255, null=True)),
                (
                    "container_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="MethodName",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("meta_data_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="MethodStart",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="OverviewComment",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("comment_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Pipette",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("solution", models.CharField(max_length=255, null=True)),
                ("volume", models.CharField(max_length=255, null=True)),
                (
                    "min_aspirate_mix_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "min_dispense_mix_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Rest",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("time", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="RuntimeComment",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("comment_text", models.TextField(null=True)),
                (
                    "wait_for_user_confirmation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="Shake",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("time", models.CharField(max_length=255, null=True)),
                ("shaking_rpm", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="SilentComment",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("comment_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="SplitWorklist",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("left_container_name", models.CharField(max_length=255, null=True)),
                (
                    "left_container_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("right_container_name", models.CharField(max_length=255, null=True)),
                (
                    "right_container_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("container_choice", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="ValidModality",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("meta_data_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
        migrations.CreateModel(
            name="ValidProjectCode",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("meta_data_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
    ]
