# Generated by Django 5.1.1 on 2024-09-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockbase',
            name='column',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockbase',
            name='row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockbase',
            name='left_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='block.blockbase'),
        ),
        migrations.AlterField(
            model_name='blockbase',
            name='left_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='block.blockbase'),
        ),
        migrations.AlterField(
            model_name='blockbase',
            name='middle_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='block.blockbase'),
        ),
        migrations.AlterField(
            model_name='blockbase',
            name='middle_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='block.blockbase'),
        ),
        migrations.AlterField(
            model_name='blockbase',
            name='right_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='block.blockbase'),
        ),
        migrations.AlterField(
            model_name='blockbase',
            name='right_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='block.blockbase'),
        ),
    ]
