# Generated by Django 5.1.1 on 2024-09-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('meta_data_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('meta_data_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='ConcentrationMax',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('constraint_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='ConcentrationMin',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('constraint_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='INXNumber',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('meta_data_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('meta_data_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='OverviewComment',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('comment_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='RuntimeComment',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('comment_text', models.TextField()),
                ('wait_for_user_confirmation', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='SampleNumberMax',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('constraint_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='SampleNumberMin',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('constraint_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('meta_data_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='SilentComment',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('comment_text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
    ]
