# Generated by Django 5.1.1 on 2024-09-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_blockbase_column_blockbase_row_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateContainer',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('container_name', models.CharField(max_length=255)),
                ('container_type', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='SplitWorklist',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('left_container_name', models.CharField(max_length=255)),
                ('left_container_type', models.CharField(default='', max_length=255)),
                ('right_container_name', models.CharField(max_length=255)),
                ('right_container_type', models.CharField(default='', max_length=255)),
                ('container_choice', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
    ]
