# Generated by Django 5.1.2 on 2024-10-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_project_rename_inxnumber_documentnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='meta_data_text',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='meta_data_text',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='documentnumber',
            old_name='meta_data_text',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='modality',
            old_name='meta_data_text',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='meta_data_text',
            new_name='value',
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
