# Generated by Django 5.1.1 on 2024-09-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_author_category_concentrationmax_concentrationmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dilute',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('solution', models.CharField(max_length=255)),
                ('target_concentration', models.CharField(max_length=255)),
                ('target_volume', models.CharField(max_length=255)),
                ('min_aspirate_mix_cycles', models.CharField(blank=True, max_length=255)),
                ('min_dispense_mix_cycles', models.CharField(blank=True, max_length=255)),
                ('max_source_volume', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='Incubate',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('temperature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='IncubateAndShake',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('temperature', models.CharField(max_length=255)),
                ('shaking_rpm', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='MeasureConcentration',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('output_worklist_column', models.CharField(max_length=255)),
                ('extinction_coefficient', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='Pipette',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('solution', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('min_aspirate_mix_cycles', models.CharField(blank=True, max_length=255)),
                ('min_dispense_mix_cycles', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.CreateModel(
            name='Shake',
            fields=[
                ('blockbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.blockbase')),
                ('shaking_rpm', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('block.blockbase',),
        ),
        migrations.AlterField(
            model_name='activatecontainer',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='merge',
            name='container_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='splitworklist',
            name='left_container_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='splitworklist',
            name='right_container_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
