# Generated by Django 5.1.2 on 2024-10-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0007_remove_pipette_volume_ul_pipette_volume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concentrationmin",
            name="blockbase_ptr",
        ),
        migrations.RemoveField(
            model_name="samplenumbermax",
            name="blockbase_ptr",
        ),
        migrations.RemoveField(
            model_name="samplenumbermin",
            name="blockbase_ptr",
        ),
        migrations.DeleteModel(
            name="ConcentrationMax",
        ),
        migrations.DeleteModel(
            name="ConcentrationMin",
        ),
        migrations.DeleteModel(
            name="SampleNumberMax",
        ),
        migrations.DeleteModel(
            name="SampleNumberMin",
        ),
    ]
