# Generated by Django 5.1.2 on 2024-10-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0009_blockbase_is_valid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodName",
            fields=[
                (
                    "blockbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="block.blockbase",
                    ),
                ),
                ("meta_data_text", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("block.blockbase",),
        ),
    ]
