# Generated by Django 5.1.2 on 2024-10-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0010_methodname"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Modality",
            new_name="ValidModality",
        ),
        migrations.RenameModel(
            old_name="Project",
            new_name="ValidProjectCode",
        ),
    ]
