# Generated by Django 4.1.6 on 2024-07-23 21:06

import abn.scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=abn.scheduler.models.get_upload_path)),
            ],
        ),
    ]
