# Generated by Django 5.0.6 on 2024-08-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labware", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labwarebase",
            name="labware_definition_direction",
            field=models.CharField(
                choices=[("Rowwise", "Rowwise"), ("Columnwise", "Columnwise")],
                default="columnwise",
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="labwarebase",
            name="z_length",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
