# Generated by Django 4.1.6 on 2024-07-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HamiltonVantageTrackGripperEntryExit',
            new_name='HamiltonTrackGripperEntryExitVantage',
        ),
    ]
