# Generated by Django 5.1.2 on 2024-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                (
                    "simultaneous_tips",
                    models.PositiveSmallIntegerField(
                        help_text="How many tips can fit in the container at the same time"
                    ),
                ),
                (
                    "max_volume",
                    models.FloatField(help_text="Max volume of a container."),
                ),
                (
                    "dead_volume",
                    models.FloatField(
                        help_text="Minimum volume required in a container for successful aspiration."
                    ),
                ),
                (
                    "shape_definition",
                    models.JSONField(
                        help_text="A list of (volume uL, height mm) pairs that define the shape of a container. Pipetting accurately in a container requires an accurate container shape definition."
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
    ]
