# Generated by Django 5.1.2 on 2024-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "identifier",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "simultaneous_tips",
                    models.SmallIntegerField(
                        help_text="How many tips can fit in the container position at a the same time."
                    ),
                ),
                (
                    "max_volume",
                    models.SmallIntegerField(help_text="Max volume of a container."),
                ),
                (
                    "dead_volume",
                    models.SmallIntegerField(
                        help_text="Minimum volume required in a container for successful aspiration."
                    ),
                ),
                (
                    "shape_definition",
                    models.JSONField(
                        help_text="A list of (volume uL, height mm) pairs, volume ordered, that define the shape of a container. Pipetting accurately in a container requires an accurate container shape definition."
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
    ]
