# Generated by Django 5.1.2 on 2024-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="identifier",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
