# Generated by Django 5.1.2 on 2024-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0003_alter_container_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="shape_definition",
            field=models.JSONField(
                default=[
                    ("Volume 1", "Height 1"),
                    ("Volume 2", "Height 2"),
                    ("Volume ...", "Height ..."),
                ],
                help_text="A list of [volume uL, height mm] pairs, in volume order, that define the shape of a container. Pipetting accurately in a container requires an accurate container shape definition.",
            ),
        ),
    ]
