# Generated by Django 5.1.2 on 2024-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0004_alter_container_shape_definition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="simultaneous_tips",
            field=models.PositiveSmallIntegerField(
                help_text="How many tips can fit in the container at the same time."
            ),
        ),
    ]
