# Generated by Django 5.1.2 on 2024-11-12 15:08

import django.db.models.deletion
import hal.labware.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("container", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labware",
            fields=[
                (
                    "identifier",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "x_y_z_dimensions",
                    models.JSONField(
                        default=hal.labware.models._x_y_z_dimensions_default,
                        help_text="Plates are not inheritantly a cube. This property defines how the rectangular shape of the plate changes across z heights. Labware is assumed to be landscape such that X is length of the long side (ex. 127mm) and Y is the length of the short side (ex. 82mm).",
                        verbose_name="X Y Z dimensions",
                    ),
                ),
                (
                    "short_side_z_grip_heights",
                    models.JSONField(
                        default=hal.labware.models._grip_regions_default,
                        help_text="Which Z heights are acceptable to be gripped on the short side when transported. Relative to bottom.",
                        verbose_name="Short side Z grip heights",
                    ),
                ),
                (
                    "long_side_z_grip_heights",
                    models.JSONField(
                        default=hal.labware.models._grip_regions_default,
                        help_text="Which Z heights are acceptable to be gripped on the long side when transported. Relative to bottom.",
                        verbose_name="Long side Z grip heights",
                    ),
                ),
                (
                    "addressable_rows",
                    models.PositiveSmallIntegerField(
                        help_text="How many container rows the labware item has. Labware definition specific."
                    ),
                ),
                (
                    "addressable_columns",
                    models.PositiveSmallIntegerField(
                        help_text="How many container columns the labware item has. Labware definition specific."
                    ),
                ),
                (
                    "addressing_direction",
                    models.CharField(
                        choices=[
                            ("Column-wise", "Column-wise"),
                            ("Row-wise", "Row-wise"),
                        ],
                        help_text="How the container positions are ordered. Labware definition specific.",
                        max_length=11,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
        migrations.CreateModel(
            name="NonPipettableLabware",
            fields=[
                (
                    "labware_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="labware.labware",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("labware.labware",),
        ),
        migrations.CreateModel(
            name="StackedLabwareZHeightChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("z_height_change", models.FloatField()),
                (
                    "bottom_labware",
                    models.ForeignKey(
                        help_text="The bottom labware of the stack.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stackedlabwarezheightchangebottom_set",
                        to="labware.labware",
                    ),
                ),
                (
                    "top_labware",
                    models.ForeignKey(
                        help_text="The top labware of the stack.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stackedlabwarezheightchangetop_set",
                        to="labware.labware",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipettableLabware",
            fields=[
                (
                    "labware_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="labware.labware",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("labware.labware",),
        ),
    ]
