# Generated by Django 5.0 on 2024-11-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labware", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stackedlabwarezheightchange",
            name="z_height_change",
            field=models.FloatField(
                help_text="How much does the top labware nest into the bottom labware. Should always be equal to or less than 0. Ex. <stacked_labware_height> - (<top labware height> + <bottom labware height>)"
            ),
        ),
    ]
