# Generated by Django 5.1.2 on 2024-11-08 21:01

import django.db.models.deletion
import hal.labware.models.labware_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labware", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="t",
            fields=[
                (
                    "labwarebase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="labware.labwarebase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=(
                "labware.labwarebase",
                hal.labware.models.labware_base.PipettableLabwareMixin,
            ),
        ),
    ]
