# Generated by Django 5.1.1 on 2024-10-02 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('storage_condition', models.CharField(choices=[('Ambient', 'Ambient'), ('Cold', 'Cold')], max_length=8)),
                ('liquid_type', models.CharField(choices=[('Aqueous', 'Aqueous'), ('Organic', 'Organic'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('viscosity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('volatility', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('homogeneity', models.CharField(choices=[('Heterogenous', 'Heterogenous'), ('Homogenous', 'Homogenous'), ('Suspension', 'Suspension'), ('Emulsion', 'Emulsion'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('component_1_name', models.CharField(blank=True, max_length=255)),
                ('component_1_amount', models.FloatField(blank=True, null=True)),
                ('component_1_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_2_name', models.CharField(blank=True, max_length=255)),
                ('component_2_amount', models.FloatField(blank=True, null=True)),
                ('component_2_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_3_name', models.CharField(blank=True, max_length=255)),
                ('component_3_amount', models.FloatField(blank=True, null=True)),
                ('component_3_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_4_name', models.CharField(blank=True, max_length=255)),
                ('component_4_amount', models.FloatField(blank=True, null=True)),
                ('component_4_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_5_name', models.CharField(blank=True, max_length=255)),
                ('component_5_amount', models.FloatField(blank=True, null=True)),
                ('component_5_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_6_name', models.CharField(blank=True, max_length=255)),
                ('component_6_amount', models.FloatField(blank=True, null=True)),
                ('component_6_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_7_name', models.CharField(blank=True, max_length=255)),
                ('component_7_amount', models.FloatField(blank=True, null=True)),
                ('component_7_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_8_name', models.CharField(blank=True, max_length=255)),
                ('component_8_amount', models.FloatField(blank=True, null=True)),
                ('component_8_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_9_name', models.CharField(blank=True, max_length=255)),
                ('component_9_amount', models.FloatField(blank=True, null=True)),
                ('component_9_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionPropertyPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('liquid_type', models.CharField(choices=[('Aqueous', 'Aqueous'), ('Organic', 'Organic'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('viscosity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('volatility', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('homogeneity', models.CharField(choices=[('Heterogenous', 'Heterogenous'), ('Homogenous', 'Homogenous'), ('Suspension', 'Suspension'), ('Emulsion', 'Emulsion'), ('Auto-determine', 'Auto-determine')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('storage_condition', models.CharField(choices=[('Ambient', 'Ambient'), ('Cold', 'Cold')], max_length=8)),
                ('liquid_type', models.CharField(choices=[('Aqueous', 'Aqueous'), ('Organic', 'Organic'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('viscosity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('volatility', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('homogeneity', models.CharField(choices=[('Heterogenous', 'Heterogenous'), ('Homogenous', 'Homogenous'), ('Suspension', 'Suspension'), ('Emulsion', 'Emulsion'), ('Auto-determine', 'Auto-determine')], max_length=14)),
                ('component_1_name', models.CharField(blank=True, max_length=255)),
                ('component_1_amount', models.FloatField(blank=True, null=True)),
                ('component_1_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_2_name', models.CharField(blank=True, max_length=255)),
                ('component_2_amount', models.FloatField(blank=True, null=True)),
                ('component_2_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_3_name', models.CharField(blank=True, max_length=255)),
                ('component_3_amount', models.FloatField(blank=True, null=True)),
                ('component_3_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_4_name', models.CharField(blank=True, max_length=255)),
                ('component_4_amount', models.FloatField(blank=True, null=True)),
                ('component_4_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_5_name', models.CharField(blank=True, max_length=255)),
                ('component_5_amount', models.FloatField(blank=True, null=True)),
                ('component_5_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_6_name', models.CharField(blank=True, max_length=255)),
                ('component_6_amount', models.FloatField(blank=True, null=True)),
                ('component_6_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_7_name', models.CharField(blank=True, max_length=255)),
                ('component_7_amount', models.FloatField(blank=True, null=True)),
                ('component_7_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_8_name', models.CharField(blank=True, max_length=255)),
                ('component_8_amount', models.FloatField(blank=True, null=True)),
                ('component_8_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('component_9_name', models.CharField(blank=True, max_length=255)),
                ('component_9_amount', models.FloatField(blank=True, null=True)),
                ('component_9_unit', models.CharField(blank=True, choices=[('uL', 'uL'), ('mg', 'mg'), ('units', 'units')], max_length=5)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='method.usermethodworkbookbase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
