# Generated by Django 5.1.1 on 2024-10-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0001_initial'),
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedComponent',
            fields=[
                ('componentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solution.componentbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('solution.componentbase',),
        ),
        migrations.CreateModel(
            name='UserDefinedComponent',
            fields=[
                ('componentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solution.componentbase')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='method.usermethodworkbookbase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('solution.componentbase',),
        ),
    ]
