# Generated by Django 5.1.1 on 2024-10-03 21:49

from django.db import migrations, models

import solution.models.user_defined_component_base


class Migration(migrations.Migration):

    dependencies = [
        ("method", "0001_initial"),
        ("solution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdefinedcomponentbase",
            name="method",
            field=models.ForeignKey(
                on_delete=solution.models.user_defined_component_base.NON_POLYMORPHIC_CASCADE,
                to="method.MethodWorkbookBase",
            ),
        ),
    ]
