# Generated by Django 5.1.1 on 2024-09-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_alter_predefinedsolution_component_1_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_1_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_2_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_3_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_4_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_5_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_6_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_7_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_8_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predefinedsolution',
            name='component_9_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_1_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_2_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_3_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_4_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_5_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_6_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_7_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_8_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinedsolution',
            name='component_9_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
