# Generated by Django 5.1.1 on 2024-09-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_alter_predefinedsolution_component_1_volume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_1_volume',
            new_name='component_1_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_2_volume',
            new_name='component_2_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_3_volume',
            new_name='component_3_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_4_volume',
            new_name='component_4_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_5_volume',
            new_name='component_5_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_6_volume',
            new_name='component_6_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_7_volume',
            new_name='component_7_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_8_volume',
            new_name='component_8_amount',
        ),
        migrations.RenameField(
            model_name='predefinedsolution',
            old_name='component_9_volume',
            new_name='component_9_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_1_volume',
            new_name='component_1_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_2_volume',
            new_name='component_2_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_3_volume',
            new_name='component_3_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_4_volume',
            new_name='component_4_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_5_volume',
            new_name='component_5_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_6_volume',
            new_name='component_6_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_7_volume',
            new_name='component_7_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_8_volume',
            new_name='component_8_amount',
        ),
        migrations.RenameField(
            model_name='userdefinedsolution',
            old_name='component_9_volume',
            new_name='component_9_amount',
        ),
    ]
