# Generated by Django 4.1.6 on 2024-08-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrierbase',
            old_name='track_end',
            new_name='width',
        ),
    ]
