# Generated by Django 5.1.2 on 2024-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("method", "0002_templatemethodworkbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="methodworkbookbase",
            name="is_full_read",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
