# Generated by Django 5.1.2 on 2024-10-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("method", "0004_testingmethodworkbook_test_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testingmethodworkbook",
            name="test_progress",
        ),
        migrations.AddField(
            model_name="methodworkbookbase",
            name="validation_progress",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
