# Generated by Django 5.1.2 on 2024-10-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("method", "0005_remove_testingmethodworkbook_test_progress_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="methodworkbookbase",
            old_name="is_full_read",
            new_name="is_read",
        ),
        migrations.RemoveField(
            model_name="methodworkbookbase",
            name="validation_progress",
        ),
    ]
