# Generated by Django 5.1.2 on 2024-10-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("method", "0007_rename_is_read_methodworkbookbase_is_method_read_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="methodworkbookbase",
            old_name="is_method_read",
            new_name="assign_labware_checkpoint",
        ),
        migrations.RenameField(
            model_name="methodworkbookbase",
            old_name="is_solutions_read",
            new_name="containers_created_checkpoint",
        ),
        migrations.RenameField(
            model_name="methodworkbookbase",
            old_name="is_worklist_read",
            new_name="containers_pipetted_checkpoint",
        ),
        migrations.AddField(
            model_name="methodworkbookbase",
            name="devices_possible_checkpoint",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="methodworkbookbase",
            name="meta_present_checkpoint",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="methodworkbookbase",
            name="method_read_checkpoint",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="methodworkbookbase",
            name="solutions_read_checkpoint",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="methodworkbookbase",
            name="worklist_read_checkpoint",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
