# Generated by Django 5.1.2 on 2024-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "method",
            "0008_rename_is_method_read_methodworkbookbase_assign_labware_checkpoint_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="methodworkbookbase",
            name="is_valid",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
