# Generated by Django 5.1.2 on 2024-10-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("method", "0009_methodworkbookbase_is_valid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="methodworkbookbase",
            old_name="meta_present_checkpoint",
            new_name="method_validated_checkpoint",
        ),
    ]
