# Generated by Django 5.1.1 on 2024-09-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Silly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('log_source', models.IntegerField(choices=[(1, 'Plh'), (2, 'Abn')])),
                ('log_level', models.IntegerField(choices=[(1, 'Debug'), (2, 'Info'), (3, 'Warning'), (4, 'Critical'), (5, 'Error')])),
                ('meta_info', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['time_stamp'],
            },
        ),
    ]
