# Generated by Django 5.0.6 on 2024-08-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debug", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="traceentry",
            old_name="device_identifier",
            new_name="device",
        ),
        migrations.AlterField(
            model_name="traceentry",
            name="method",
            field=models.CharField(max_length=100),
        ),
    ]
