# Generated by Django 4.1.6 on 2024-08-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0003_rename_device_identifier_traceentry_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traceentry',
            name='device',
        ),
        migrations.RemoveField(
            model_name='traceentry',
            name='method',
        ),
        migrations.AddField(
            model_name='traceentry',
            name='meta_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
