# Generated by Django 4.1.6 on 2024-08-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0004_remove_traceentry_device_remove_traceentry_method_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TraceEntry',
            new_name='Trace',
        ),
    ]
