# Generated by Django 4.1.6 on 2024-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0005_rename_traceentry_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
