# Generated by Django 5.1.2 on 2024-11-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("deck", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(editable=False, max_length=255)),
                (
                    "deck_position",
                    models.SmallIntegerField(
                        help_text="Typically the starting carrier number. But for decks without a positions this is flexible (NOTE: from left to right)."
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        help_text="Which deck is this carrier assigned to?",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deck.deck",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
                "unique_together": {("deck", "deck_position")},
            },
        ),
        migrations.CreateModel(
            name="MoveableCarrier",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="carrier.carrier",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("carrier.carrier",),
        ),
        migrations.CreateModel(
            name="StationaryCarrier",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="carrier.carrier",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("carrier.carrier",),
        ),
        migrations.CreateModel(
            name="HamiltonAutoloadCarrier",
            fields=[
                (
                    "moveablecarrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="carrier.moveablecarrier",
                    ),
                ),
                ("carrier_labware_id", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("carrier.moveablecarrier",),
        ),
    ]
