# Generated by Django 5.0 on 2024-11-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarrierBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(editable=False, max_length=255)),
                (
                    "deck_position",
                    models.SmallIntegerField(
                        help_text="Typically the starting carrier number. But for decks without a positions this is flexible (NOTE: from left to right)."
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
        migrations.CreateModel(
            name="MoveableCarrier",
            fields=[
                (
                    "carrierbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="carrier.carrierbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("carrier.carrierbase",),
        ),
        migrations.CreateModel(
            name="StationaryCarrier",
            fields=[
                (
                    "carrierbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="carrier.carrierbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("carrier.carrierbase",),
        ),
    ]
