# Generated by Django 5.1.2 on 2024-11-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContainerBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_required_volume", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ActivatedContainer",
            fields=[
                (
                    "containerbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deck.containerbase",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("deck.containerbase",),
        ),
        migrations.CreateModel(
            name="SolutionContainer",
            fields=[
                (
                    "containerbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deck.containerbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("deck.containerbase",),
        ),
    ]
