# Generated by Django 5.1.2 on 2024-10-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "method",
            "0010_rename_meta_present_checkpoint_methodworkbookbase_method_validated_checkpoint",
        ),
        ("solution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_required_volume", models.FloatField()),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="method.methodworkbookbase",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ActivatedContainer",
            fields=[
                (
                    "containerbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deck.containerbase",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("deck.containerbase",),
        ),
        migrations.CreateModel(
            name="SolutionContainer",
            fields=[
                (
                    "containerbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deck.containerbase",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solution.componentbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("deck.containerbase",),
        ),
    ]
