# Generated by Django 5.1.2 on 2024-11-11 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("deck", "0001_initial"),
        ("method", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerbase",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="method.methodworkbookbase",
            ),
        ),
        migrations.AddField(
            model_name="containerbase",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
