# Generated by Django 5.1.2 on 2024-11-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deck", "0002_initial"),
        ("solution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutioncontainer",
            name="solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="solution.componentbase"
            ),
        ),
    ]
