# Generated by Django 5.0 on 2024-11-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carrier_location", "0001_initial"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportablecarrierlocationconfig",
            name="pickup_options",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transport.transportpickupoptionsbase",
            ),
        ),
        migrations.AddField(
            model_name="transportablecarrierlocationconfig",
            name="place_options",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transport.transportplaceoptionsbase",
            ),
        ),
        migrations.AddField(
            model_name="transportablecarrierlocationconfig",
            name="transport_device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transport.transportbase",
            ),
        ),
        migrations.AddField(
            model_name="transportablecarrierlocation",
            name="transport_configs",
            field=models.ManyToManyField(
                to="carrier_location.transportablecarrierlocationconfig"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carrierlocationbase",
            unique_together={("carrier", "carrier_position")},
        ),
        migrations.AlterUniqueTogether(
            name="transportablecarrierlocationconfig",
            unique_together={("transport_device", "pickup_options", "place_options")},
        ),
    ]
