# Generated by Django 5.0.6 on 2024-08-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrier", "0001_initial"),
        ("deck_location", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decklocationbase",
            name="carrier",
            field=models.ForeignKey(
                db_column="carrier",
                on_delete=django.db.models.deletion.CASCADE,
                to="carrier.carrierbase",
            ),
        ),
    ]
