# Generated by Django 5.0.6 on 2024-08-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrier", "0001_initial"),
        ("deck_location", "0003_alter_decklocationbase_carrier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decklocationbase",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="carrier.carrierbase"
            ),
        ),
    ]
