# Generated by Django 5.0 on 2024-11-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck_location", "0002_alter_decklocationbase_carrier_and_more"),
        ("transport", "0003_alter_transportbase_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportableDeckLocationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.transportpickupoptionsbase",
                    ),
                ),
                (
                    "place_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.transportplaceoptionsbase",
                    ),
                ),
                (
                    "transport_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.transportbase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportableDeckLocation",
            fields=[
                (
                    "decklocationbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="deck_location.decklocationbase",
                    ),
                ),
                (
                    "transport_configs",
                    models.ManyToManyField(
                        to="deck_location.transportabledecklocationconfig"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("deck_location.decklocationbase",),
        ),
    ]
