# Generated by Django 5.1.2 on 2024-11-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deckbase",
            name="identifier",
            field=models.CharField(
                help_text="Unique name to distinguish this deck from other decks.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subdeck",
            name="parent_deck",
            field=models.ForeignKey(
                help_text="Deck on which this sub deck is located.",
                on_delete=django.db.models.deletion.CASCADE,
                to="deck.deck",
            ),
        ),
    ]
