# Generated by Django 5.0 on 2024-11-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backend", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(editable=False, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.backendbase",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
        migrations.CreateModel(
            name="TransportPickupOptionsBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="TransportPlaceOptionsBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="HamiltonCOREGripper",
            fields=[
                (
                    "transportbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportbase",
                    ),
                ),
                ("gripper_labware_id", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Hamilton CORE Gripper",
                "verbose_name_plural": "Hamilton CORE Grippers",
            },
            bases=("transport.transportbase",),
        ),
        migrations.CreateModel(
            name="HamiltonInternalPlateGripperComplexMovement",
            fields=[
                (
                    "transportbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("transport.transportbase",),
        ),
        migrations.CreateModel(
            name="HamiltonInternalPlateGripperSimpleMovement",
            fields=[
                (
                    "transportbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("transport.transportbase",),
        ),
        migrations.CreateModel(
            name="HamiltonVantageTrackGripperTaughtMovement",
            fields=[
                (
                    "transportbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("transport.transportbase",),
        ),
        migrations.CreateModel(
            name="HamiltonInternalPlateGripperComplexMovementPlaceOptions",
            fields=[
                (
                    "transportplaceoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportplaceoptionsbase",
                    ),
                ),
                ("retract_distance", models.FloatField()),
                (
                    "labware_orientation",
                    models.CharField(
                        choices=[
                            ("Positive Y Direction", "Positive Y Direction"),
                            ("Negative X Direction", "Negative X Direction"),
                            ("Negative Y Direction", "Negative Y Direction"),
                            ("Positive X Direction", "Positive X Direction"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("transport.transportplaceoptionsbase",),
        ),
        migrations.CreateModel(
            name="HamiltonInternalPlateGripperSimpleMovementPlaceOptions",
            fields=[
                (
                    "transportplaceoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportplaceoptionsbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("transport.transportplaceoptionsbase",),
        ),
        migrations.CreateModel(
            name="HamiltonCOREGripperPickupOptions",
            fields=[
                (
                    "transportpickupoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportpickupoptionsbase",
                    ),
                ),
                (
                    "grip_force",
                    models.CharField(
                        choices=[
                            ("Grip Force 0", "Grip Force 0"),
                            ("Grip Force 1", "Grip Force 1"),
                            ("Grip Force 2", "Grip Force 2"),
                            ("Grip Force 3", "Grip Force 3"),
                            ("Grip Force 4", "Grip Force 4"),
                            ("Grip Force 5", "Grip Force 5"),
                            ("Grip Force 6", "Grip Force 6"),
                            ("Grip Force 7", "Grip Force 7"),
                            ("Grip Force 8", "Grip Force 8"),
                            ("Grip Force 9", "Grip Force 9"),
                        ],
                        default="Grip Force 5",
                        max_length=25,
                    ),
                ),
                ("grip_speed", models.FloatField(default=277.8)),
                ("z_speed", models.FloatField(default=128.7)),
                ("check_plate_exists", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {
                    ("grip_force", "grip_speed", "z_speed", "check_plate_exists")
                },
            },
            bases=("transport.transportpickupoptionsbase",),
        ),
        migrations.CreateModel(
            name="HamiltonInternalPlateGripperComplexMovementPickupOptions",
            fields=[
                (
                    "transportpickupoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportpickupoptionsbase",
                    ),
                ),
                (
                    "grip_mode",
                    models.CharField(
                        choices=[
                            ("Grip on short side", "Grip on short side"),
                            ("Grip on long side", "Grip on long side"),
                        ],
                        max_length=20,
                    ),
                ),
                ("retract_distance", models.FloatField()),
                ("liftup_height", models.FloatField()),
                (
                    "labware_orientation",
                    models.CharField(
                        choices=[
                            ("Positive Y Direction", "Positive Y Direction"),
                            ("Negative X Direction", "Negative X Direction"),
                            ("Negative Y Direction", "Negative Y Direction"),
                            ("Positive X Direction", "Positive X Direction"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "grip_force",
                    models.CharField(
                        choices=[
                            ("Grip Force 0", "Grip Force 0"),
                            ("Grip Force 1", "Grip Force 1"),
                            ("Grip Force 2", "Grip Force 2"),
                            ("Grip Force 3", "Grip Force 3"),
                            ("Grip Force 4", "Grip Force 4"),
                            ("Grip Force 5", "Grip Force 5"),
                            ("Grip Force 6", "Grip Force 6"),
                            ("Grip Force 7", "Grip Force 7"),
                            ("Grip Force 8", "Grip Force 8"),
                            ("Grip Force 9", "Grip Force 9"),
                        ],
                        default="Grip Force 5",
                        max_length=25,
                    ),
                ),
                ("tolerance", models.FloatField(default=2)),
                ("inverse_grip", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {
                    (
                        "grip_mode",
                        "retract_distance",
                        "liftup_height",
                        "labware_orientation",
                        "grip_force",
                        "tolerance",
                        "inverse_grip",
                    )
                },
            },
            bases=("transport.transportpickupoptionsbase",),
        ),
        migrations.CreateModel(
            name="HamiltonInternalPlateGripperSimpleMovementPickupOptions",
            fields=[
                (
                    "transportpickupoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportpickupoptionsbase",
                    ),
                ),
                (
                    "grip_mode",
                    models.CharField(
                        choices=[
                            ("Grip on short side", "Grip on short side"),
                            ("Grip on long side", "Grip on long side"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "grip_force",
                    models.CharField(
                        choices=[
                            ("Grip Force 0", "Grip Force 0"),
                            ("Grip Force 1", "Grip Force 1"),
                            ("Grip Force 2", "Grip Force 2"),
                            ("Grip Force 3", "Grip Force 3"),
                            ("Grip Force 4", "Grip Force 4"),
                            ("Grip Force 5", "Grip Force 5"),
                            ("Grip Force 6", "Grip Force 6"),
                            ("Grip Force 7", "Grip Force 7"),
                            ("Grip Force 8", "Grip Force 8"),
                            ("Grip Force 9", "Grip Force 9"),
                        ],
                        default="Grip Force 5",
                        max_length=25,
                    ),
                ),
                ("tolerance", models.FloatField(default=2)),
                ("inverse_grip", models.BooleanField()),
            ],
            options={
                "unique_together": {
                    ("grip_mode", "grip_force", "tolerance", "inverse_grip")
                },
            },
            bases=("transport.transportpickupoptionsbase",),
        ),
        migrations.CreateModel(
            name="HamiltonVantageTrackGripperTaughtMovementPickupOptions",
            fields=[
                (
                    "transportpickupoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportpickupoptionsbase",
                    ),
                ),
                ("taught_path", models.CharField(max_length=255, unique=True)),
                ("grip_force_percent", models.FloatField()),
                ("movement_speed_percent", models.FloatField()),
                ("coordinated_movement", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {
                    (
                        "taught_path",
                        "grip_force_percent",
                        "movement_speed_percent",
                        "coordinated_movement",
                    )
                },
            },
            bases=("transport.transportpickupoptionsbase",),
        ),
        migrations.CreateModel(
            name="HamiltonCOREGripperPlaceOptions",
            fields=[
                (
                    "transportplaceoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportplaceoptionsbase",
                    ),
                ),
                (
                    "x_acceleration_level",
                    models.CharField(
                        choices=[
                            ("Level 1", "Level 1"),
                            ("Level 2", "Level 2"),
                            ("Level 3", "Level 3"),
                            ("Level 4", "Level 4"),
                            ("Level 5", "Level 5"),
                        ],
                        default="Level 4",
                        max_length=25,
                    ),
                ),
                ("z_speed", models.FloatField(default=128.7)),
                ("plate_press_on_distance", models.FloatField(default=1)),
                ("check_plate_exists", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {
                    (
                        "x_acceleration_level",
                        "z_speed",
                        "plate_press_on_distance",
                        "check_plate_exists",
                    )
                },
            },
            bases=("transport.transportplaceoptionsbase",),
        ),
        migrations.CreateModel(
            name="HamiltonVantageTrackGripperTaughtMovementPlaceOptions",
            fields=[
                (
                    "transportplaceoptionsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transport.transportplaceoptionsbase",
                    ),
                ),
                ("taught_path", models.CharField(max_length=255, unique=True)),
                ("movement_speed_percent", models.FloatField()),
                ("coordinated_movement", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {
                    ("taught_path", "movement_speed_percent", "coordinated_movement")
                },
            },
            bases=("transport.transportplaceoptionsbase",),
        ),
    ]
