# Generated by Django 5.1.2 on 2024-11-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
        ("transport", "0002_alter_transportbase_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportbase",
            name="backend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.backendbase"
            ),
        ),
    ]
