# Generated by Django 4.1.6 on 2024-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipettablelabware',
            name='calibration_points',
            field=models.JSONField(help_text='Should be a list of dictionary values containing \'Volume\' and \'Height\' where \'Volume\' is in uL and \'Height\' is in mm. Ex. [{"Volume":0,"Height":0},{"Volume":100,"Height":10}]'),
        ),
    ]
