# Generated by Django 4.1.6 on 2024-07-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labwarebase',
            name='labware_defintion_columns',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labwarebase',
            name='labware_defintion_rows',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
