# Generated by Django 4.1.6 on 2024-07-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labware', '0002_alter_pipettablelabware_calibration_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labwarebase',
            options={'ordering': ['identifier']},
        ),
    ]
