# Generated by Django 4.1.6 on 2024-07-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labware', '0002_labwarebase_labware_defintion_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipettablelabware',
            name='calibration_points',
            field=models.JSONField(default=[{'Height': 0, 'Volume': 0}], help_text='Should be a list of dictionary values containing \'Volume\' and \'Height\' where \'Volume\' is in uL and \'Height\' is in mm. Ex. [{"Volume":0,"Height":0},{"Volume":100,"Height":10}]'),
        ),
    ]
