# Generated by Django 4.1.6 on 2024-07-12 20:00

from django.db import migrations, models
import labware.models


class Migration(migrations.Migration):

    dependencies = [
        ('labware', '0003_alter_pipettablelabware_calibration_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipettablelabware',
            name='calibration_points',
            field=models.JSONField(default=labware.models.json_default, help_text='Should be a list of dictionary values containing \'Volume\' and \'Height\' where \'Volume\' is in uL and \'Height\' is in mm. Ex. [{"Volume":0,"Height":0},{"Volume":100,"Height":10}]'),
        ),
    ]
