# Generated by Django 4.1.6 on 2024-07-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidClass',
            fields=[
                ('liquid_class_name', models.CharField(help_text='Liquid class name as defined in the Hamilton liquid class editor.', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('min_volume', models.FloatField()),
                ('max_volume', models.FloatField()),
                ('num_labware_positions', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['liquid_class_name'],
            },
        ),
        migrations.CreateModel(
            name='LiquidClassCategory',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=50)),
                ('liquid_classes', models.ManyToManyField(to='pipette.liquidclass')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
