# Generated by Django 4.1.6 on 2024-07-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipette', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidclass',
            name='num_labware_positions',
        ),
    ]
