# Generated by Django 4.1.6 on 2024-07-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pipette', '0001_initial'),
        ('tip', '0001_initial'),
        ('labware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipettetip',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tip.tipbase'),
        ),
        migrations.AddField(
            model_name='pipettebase',
            name='backend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.backendbase'),
        ),
        migrations.AddField(
            model_name='pipettebase',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pipettebase',
            name='supported_aspirate_labware',
            field=models.ManyToManyField(related_name='+', to='labware.labwarebase'),
        ),
        migrations.AddField(
            model_name='pipettebase',
            name='supported_dispense_labware',
            field=models.ManyToManyField(related_name='+', to='labware.labwarebase'),
        ),
        migrations.AddField(
            model_name='pipettebase',
            name='supported_tips',
            field=models.ManyToManyField(to='pipette.pipettetip'),
        ),
        migrations.AddField(
            model_name='liquidclasscategory',
            name='liquid_classes',
            field=models.ManyToManyField(to='pipette.liquidclass'),
        ),
        migrations.CreateModel(
            name='HamiltonPortraitCORE8SimpleContentDispense',
            fields=[
                ('hamiltonportraitcore8_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipette.hamiltonportraitcore8')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pipette.hamiltonportraitcore8',),
        ),
    ]
