# Generated by Django 4.1.6 on 2024-07-15 19:00

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labware', '0004_alter_pipettablelabware_calibration_points'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pipette', '0003_alter_liquidclasscategory_category_pipettetip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipetteBase',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('waste_labware_id', models.CharField(max_length=100)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('supported_aspirate_labware', models.ManyToManyField(related_name='+', to='labware.labwarebase')),
                ('supported_dispense_labware', models.ManyToManyField(related_name='+', to='labware.labwarebase')),
                ('supported_tips', models.ManyToManyField(to='pipette.pipettetip')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='HamiltonPortraitCORE8',
            fields=[
                ('pipettebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipette.pipettebase')),
                ('active_channels', multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=38)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pipette.pipettebase',),
        ),
    ]
