# Generated by Django 4.1.6 on 2024-07-15 20:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pipette', '0004_alter_test_active_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='active_channels',
        ),
        migrations.AddField(
            model_name='test',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default=None, max_length=49),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
