# Generated by Django 4.1.6 on 2024-07-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipette', '0004_pipettebase_hamiltonportraitcore8'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamiltonPortraitCORE8SimpleContentDispense',
            fields=[
                ('pipettebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipette.pipettebase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pipette.pipettebase',),
        ),
    ]
