# Generated by Django 4.1.6 on 2024-07-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipette', '0005_remove_test_active_channels_test_my_field_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
