# Generated by Django 4.1.6 on 2024-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traceentry',
            old_name='level',
            new_name='log_level',
        ),
        migrations.AddField(
            model_name='traceentry',
            name='log_source',
            field=models.CharField(choices=[('PLH', 'PLH'), ('ABN', 'ABN')], default='PLH', max_length=3),
            preserve_default=False,
        ),
    ]
