# Generated by Django 4.1.6 on 2024-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceentry',
            name='log_level',
            field=models.IntegerField(choices=[(1, 'DEBUG'), (2, 'INFO'), (3, 'WARNING'), (4, 'CRITICAL'), (5, 'ERROR')]),
        ),
    ]
