# Generated by Django 4.1.6 on 2024-08-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('method', '0001_initial'),
        ('debug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceentry',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='method.usermethod'),
        ),
    ]
