# Generated by Django 4.1.6 on 2024-07-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0002_alter_log_options_log_device_log_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='device',
            new_name='device_identifier',
        ),
    ]
