# Generated by Django 4.1.6 on 2024-07-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0002_alter_traceentry_log_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceentry',
            name='log_level',
            field=models.IntegerField(choices=[(1, 'Debug'), (2, 'Info'), (3, 'Warning'), (4, 'Critical'), (5, 'Error')]),
        ),
        migrations.AlterField(
            model_name='traceentry',
            name='log_source',
            field=models.IntegerField(choices=[(1, 'Plh'), (2, 'Abn')]),
        ),
    ]
