# Generated by Django 4.1.6 on 2024-07-26 13:53

from django.db import migrations, models
import scheduler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('emails', models.CharField(max_length=100)),
                ('phone_numbers', models.CharField(blank=True, max_length=100)),
                ('completion_time', models.DateTimeField()),
                ('file', models.FileField(max_length=255, upload_to=scheduler.models.get_upload_path)),
            ],
        ),
    ]
