# Generated by Django 4.1.6 on 2024-08-01 15:05

from django.db import migrations, models
import scheduler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(choices=[('Reading', 'Reading'), ('Running', 'Running'), ('Paused', 'Paused'), ('Waiting on User', 'Waiting on User'), ('Complete', 'Complete'), ('Aborted', 'Aborted')], default='Reading', max_length=15)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('emails', models.CharField(max_length=100)),
                ('phone_numbers', models.CharField(blank=True, max_length=100)),
                ('completion_time', models.DateTimeField()),
                ('file', models.FileField(max_length=255, upload_to=scheduler.models.get_upload_path)),
            ],
        ),
    ]
