# Generated by Django 4.1.6 on 2024-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='excel_file',
            field=models.FileField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
