# Generated by Django 4.1.6 on 2024-07-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuedmethod',
            old_name='file_name',
            new_name='filename',
        ),
    ]
