# Generated by Django 4.1.6 on 2024-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_file_name_queuedmethod_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmethod',
            name='state',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Aborted', 'Aborted'), ('Notification', 'Notification'), ('Running', 'Running'), ('Paused', 'Paused'), ('Not Running', 'Not Running'), ('Paused', 'Paused'), ('Deck Loading', 'Deck Loading')], default='Not Running', max_length=12),
            preserve_default=False,
        ),
    ]
