# Generated by Django 5.1.2 on 2024-11-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("carrier_location", "0001_initial"),
        ("labware", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutItemBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(editable=False, max_length=255)),
                (
                    "carrier_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrier_location.CarrierLocationbase",
                    ),
                ),
                (
                    "labware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labware.labwarebase",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
                "unique_together": {("carrier_location", "labware")},
            },
        ),
    ]
