# Generated by Django 5.1.2 on 2024-11-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrier_location", "0002_alter_CarrierLocationbase_carrier_and_more"),
        ("labware", "0001_initial"),
        ("layout_item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layoutitembase",
            name="carrier_location",
            field=models.ForeignKey(
                help_text="Which deck location is this layout item located?",
                on_delete=django.db.models.deletion.CASCADE,
                to="carrier_location.CarrierLocationbase",
            ),
        ),
        migrations.AlterField(
            model_name="layoutitembase",
            name="labware",
            field=models.ForeignKey(
                help_text="What is the labware of this layout item?",
                on_delete=django.db.models.deletion.CASCADE,
                to="labware.labwarebase",
            ),
        ),
    ]
