# Generated by Django 4.1.6 on 2024-08-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HamiltonMicrolabStar',
            new_name='MicrolabStar',
        ),
        migrations.RenameModel(
            old_name='HamiltonTrackGripperEntryExitVantage',
            new_name='VantageTrackGripperEntryExit',
        ),
        migrations.AddField(
            model_name='stunner',
            name='port',
            field=models.SmallIntegerField(default=80),
            preserve_default=False,
        ),
    ]
