# Generated by Django 4.1.6 on 2024-07-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamiltoncoregrippergetoptions',
            name='check_plate_exists',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hamiltoninternalplategrippergetoptions',
            name='grip_mode',
            field=models.CharField(choices=[('GripOnShortSide', 'Grip On Short Side'), ('GripOnLongSide', 'Grip On Long Side')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hamiltoninternalplategrippergetoptions',
            name='labware_orientation',
            field=models.CharField(choices=[('NegativeYAxis', 'Negative Y Axis'), ('PositiveXAxis', 'Positive X Axis'), ('PositiveYAxis', 'Positive Y Axis'), ('NegativeXAxis', 'Negative X Axis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hamiltoninternalplategripperplaceoptions',
            name='labware_orientation',
            field=models.CharField(choices=[('NegativeYAxis', 'Negative Y Axis'), ('PositiveXAxis', 'Positive X Axis'), ('PositiveYAxis', 'Positive Y Axis'), ('NegativeXAxis', 'Negative X Axis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vantagetrackgrippergetoptions',
            name='labware_orientation',
            field=models.CharField(choices=[('NegativeYAxis', 'Negative Y Axis'), ('PositiveXAxis', 'Positive X Axis'), ('PositiveYAxis', 'Positive Y Axis'), ('NegativeXAxis', 'Negative X Axis')], max_length=20),
        ),
    ]
