# Generated by Django 4.1.6 on 2024-07-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeable_container', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closeablecontainerbase',
            old_name='supported_labware',
            new_name='supported_labwares',
        ),
        migrations.AlterField(
            model_name='closeablecontainerbase',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
