# Generated by Django 4.1.6 on 2024-07-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labware', '0001_initial'),
        ('closeable_container', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeablecontainerbase',
            name='supported_labwares',
            field=models.ManyToManyField(to='labware.labwarebase'),
        ),
    ]
