# Generated by Django 4.1.6 on 2024-07-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0002_lid_plate_coverableplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverableplate',
            old_name='lids',
            new_name='lid_id',
        ),
    ]
