# Generated by Django 4.1.6 on 2024-07-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0003_rename_lids_coverableplate_lid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverableplate',
            name='lid_id',
            field=models.ForeignKey(db_column='lid_id', on_delete=django.db.models.deletion.CASCADE, to='layout_item.lid'),
        ),
    ]
