# Generated by Django 4.1.6 on 2024-07-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0004_alter_coverableplate_lid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverableplate',
            name='lid_id',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='layout_item.lid'),
        ),
    ]
