# Generated by Django 4.1.6 on 2024-07-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0005_alter_coverableplate_lid_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoverablePlate',
        ),
    ]
