# Generated by Django 4.1.6 on 2024-07-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0006_delete_coverableplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverablePlate',
            fields=[
                ('layoutitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layout_item.layoutitembase')),
                ('lid_id', models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='layout_item.lid')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('layout_item.layoutitembase',),
        ),
    ]
