# Generated by Django 4.1.6 on 2024-07-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0007_coverableplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverableplate',
            name='lid_id',
        ),
        migrations.AddField(
            model_name='coverableplate',
            name='lid_ptr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='layout_item.lid'),
            preserve_default=False,
        ),
    ]
