# Generated by Django 4.1.6 on 2024-07-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0008_remove_coverableplate_lid_id_coverableplate_lid_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverableplate',
            name='lid_ptr',
        ),
        migrations.AddField(
            model_name='coverableplate',
            name='lid_id',
            field=models.ForeignKey(db_column='lid_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='layout_item.lid'),
            preserve_default=False,
        ),
    ]
