# Generated by Django 4.1.6 on 2024-07-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout_item', '0010_tiprack_vacuummanifold'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverableFilterPlate',
            fields=[
                ('coverableplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layout_item.coverableplate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('layout_item.coverableplate',),
        ),
        migrations.CreateModel(
            name='FilterPlate',
            fields=[
                ('plate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layout_item.plate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('layout_item.plate',),
        ),
        migrations.AlterModelOptions(
            name='layoutitembase',
            options={'ordering': ['identifier']},
        ),
        migrations.RemoveField(
            model_name='coverableplate',
            name='layoutitembase_ptr',
        ),
        migrations.AddField(
            model_name='coverableplate',
            name='plate_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layout_item.plate'),
            preserve_default=False,
        ),
    ]
