# Generated by Django 4.1.6 on 2024-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierbase',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='carrierbase',
            name='identifier',
            field=models.CharField(default='None', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='carrierbase',
            name='num_labware_positions',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='carrierbase',
            name='track_end',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='carrierbase',
            name='track_start',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
