# Generated by Django 4.1.6 on 2024-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_remove_carrierbase_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierbase',
            name='identifier',
            field=models.CharField(default='None', help_text="Unique ID for the item. Leave as 'None' to use an autogenerated identifier.", max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
