# Generated by Django 4.1.6 on 2024-07-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0003_alter_carrierbase_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrierbase',
            options={'ordering': ['identifier']},
        ),
    ]
