# Generated by Django 4.1.6 on 2024-07-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck_location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarrierConfig',
        ),
    ]
