# Generated by Django 4.1.6 on 2024-07-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck_location', '0002_delete_carrierconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decklocationbase',
            options={'ordering': ['identifier']},
        ),
    ]
