# Generated by Django 4.1.6 on 2024-07-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck_location', '0002_transportabledecklocation_transportconfig'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportconfig',
            name='get_options',
            field=models.ManyToManyField(to='transport.transportgetoptions'),
        ),
        migrations.AddField(
            model_name='transportconfig',
            name='place_options',
            field=models.ManyToManyField(to='transport.transportplaceoptions'),
        ),
        migrations.AddField(
            model_name='transportconfig',
            name='transport_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportbase'),
        ),
        migrations.AddField(
            model_name='transportabledecklocation',
            name='transport_configs',
            field=models.ManyToManyField(to='deck_location.transportconfig'),
        ),
    ]
