# Generated by Django 4.1.6 on 2024-08-01 15:05

from django.db import migrations, models
import method.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(max_length=255, upload_to=method.models.upload_to)),
                ('activity', models.CharField(choices=[('Test', 'Test'), ('Execute', 'Execute')], default='Test', max_length=7)),
            ],
        ),
    ]
