# Generated by Django 4.1.6 on 2024-07-29 21:59

from django.db import migrations, models
import django.db.models.deletion
import method.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=method.models.get_upload_path)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='method.testmethod')),
            ],
        ),
    ]
