# Generated by Django 4.1.6 on 2024-07-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0002_testmethod_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmethod',
            name='filename',
        ),
    ]
